name: Run Check PM2

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *" # 每30分钟触发


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Run
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: go run main.go check-pm2
